import type { BookingStatus, User } from '@/lib/domain';
export type Provider = {
  id: string;
  user_id: string;
  business_name: string;
  description: string;
  category_id: string;
  area: string;
  avatar: string;
  cover: string;
  phone: string;
  verified: number;
  rating: number;
  review_count: number;
  completed: number;
  disputes: number;
  vip: number;
  featured: number;
  trusted: boolean;
  best: boolean;
  category_name: string;
  status: string;
};
export type Service = {
  id: string;
  provider_id: string;
  category_id: string;
  title: string;
  description: string;
  base_price: number;
  unit: string;
  duration: string;
  min_guests: number;
  max_guests: number;
  image: string;
  status: string;
  moderated: number;
  business_name: string;
  category_name: string;
  rating: number;
  review_count: number;
  completed: number;
  vip: number;
  featured: number;
  trusted: boolean;
  available: boolean;
};
export type Package = {
  id: string;
  service_id: string;
  name: string;
  description: string;
  price: number;
  inclusions: string;
  exclusions: string;
  duration: string;
  terms: string;
  active: number;
};
export type Bundle = {
  id: string;
  name: string;
  description: string;
  image: string;
  discount_percent: number;
  status: string;
  items: BundleItem[];
  total: number;
  original: number;
  available: boolean;
  ready: boolean;
};
export type BundleItem = {
  id: string;
  bundle_id: string;
  provider_id: string;
  package_id: string;
  price: number;
  inclusions: string;
  exclusions: string;
  terms: string;
  approval: string;
  business_name: string;
  package_name: string;
  service_title: string;
  service_id: string;
  user_id: string;
  category_id: string;
  service_status: string;
  moderated: number;
  package_active: number;
  provider_status: string;
  category_active: number;
};
export type Booking = {
  id: string;
  customer_id: string;
  bundle_id: string | null;
  title: string;
  event_date: string;
  event_type: string;
  location: string;
  guests: number;
  contact: string;
  requests: string;
  subtotal: number;
  discount: number;
  total: number;
  platform_fee: number;
  voucher_id: string | null;
  status: BookingStatus;
  escrow_status: string;
  created_at: string;
  customer_name: string;
  customer_email: string;
  voucher_code: string | null;
  items: BookingItem[];
};
export type BookingItem = {
  id: string;
  booking_id: string;
  provider_id: string;
  service_id: string;
  package_id: string;
  title: string;
  package_name: string;
  inclusions: string;
  terms: string;
  price: number;
  allocation: number;
  platform_fee: number;
  status: string;
  business_name: string;
  provider_user_id: string;
  provider_phone: string;
  review_id: string | null;
};
export type Voucher = {
  id: string;
  code: string;
  description: string;
  type: string;
  value: number;
  min_spend: number;
  max_discount: number;
  valid_from: string;
  expires_at: string;
  usage_limit: number;
  per_user_limit: number;
  rank_required: string;
  first_only: number;
  category_id: string | null;
  active: number;
  owner_id: string | null;
};
export type Review = {
  id: string;
  rating: number;
  body: string;
  created_at: string;
  customer_name: string;
  service_title: string;
  business_name: string;
};
export type SessionUser = User;
